apiVersion: v1
kind: Service
metadata:
  name: pihole-lb-service-udp
spec:
  type: LoadBalancer
  selector:
    name: pihole-app
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  externalTrafficPolicy: Local
