apiVersion: v1
kind: Service
metadata:
  name: pihole-lb-service-tcp
spec:
  type: LoadBalancer
  selector:
    name: pihole-app
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
