apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  type: NodePort
  selector:
    name: pihole-app
  ports: 
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
    nodePort: 53
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 53
  - name: web
    protocol: TCP
    port: 80
    targetPort: 80
