apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: pihole
spec:
  template:
    metadata:
      name: pihole-app
      labels: 
        name: pihole-app
    spec:
      volumes:
        - name: etcvol
          persistentVolumeClaim:
            claimName: pihole-etc-claim
        - name: dnsmvol
          persistentVolumeClaim:
            claimName: pihole-dnsm-claim
      containers:
      - name: pihole
        image: pihole/pihole:{{ .Values.imgver }}
        env:
        - name: TZ
          value: "{{ .Values.timezone }}"
        - name: WEBPASSWORD
          value: "{{ .Values.webpass }}"
        - name: PIHOLE_DNS_
          value: "{{ .Values.phdns }}"
# DEPRECATED
#        - name: DNS1
#          value: "{{ .Values.dns1 }}"
#        - name: DNS2
#          value: "{{ .Values.dns2 }}"
        - name: VIRTUAL_HOST
          value: "{{ .Values.piholeFQDN }}"
        volumeMounts:
        - name: etcvol
          mountPath: "/etc/pihole/"
        - name: dnsmvol
          mountPath: "/etc/dnsmasq.d/"
        imagePullPolicy: IfNotPresent
  replicas: 1 
  selector:
    matchLabels:
      name: pihole-app
