apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "{{ .Values.hostconfpath }}"

