apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-claim
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  volumeName: pihole-etc
  resources:
    requests:
      storage: 500Mi
